## Run this file with cloudformation
Resources:
  MyCoolUser:
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-user.html#cfn-iam-user-permissionsboundary
    Type: AWS::IAM::User
    Properties:
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/job-function/ViewOnlyAccess
      Policies:
        - PolicyName: MyCoolPolicy 
          PolicyDocument: 
            Version: 2012-10-17
            Statement:
               - Sid: IamListAccess
                 Effect: Allow
                 Action:
                  - 'iam:ListRoles'
                  - 'iam:ListUsers'
                 Resource: '*'
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-policy.html#aws-resource-iam-policy--examples
  MyInlinePolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: MyInlinePolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement: 
          - Effect: Allow
            Action: "ec2:*"
            Resource: "*"
      Users: 
        - !Ref MyCoolUser 
  MySecondInLinePolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: MySecondInLinePolicy 
      PolicyDocument:
        Version: "2012-10-17"
        Statement: 
          - Effect: Allow
            Action: "s3:*"
            Resource: "*"
      Users: 
        - !Ref MyCoolUser 