---

AWSTemplateFormatVersion: "2010-09-09"

Description: "create the s3 "

Parameters:
  BucketName: 
    Description: create the s3 
    Type: String
    Default: example-cfn-13337

Resources:
  Bucket: 
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 
        !Ref BucketName