AWSTemplateFormatVersion: "2010-09-09"
Description: "Simple MyEC2Instance"

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: "ami-0fff1b9a61dec8a5f"